let Obj =[
    {
        sale:'hot',
        URL_1:'/src/Images/product-1-1.jpg',
        URL_2:'/src/Images/product-1-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },
    {
        sale:'hot',
        URL_1:'/src/Images/product-2-1.jpg',
        URL_2:'/src/Images/product-2-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },
    {
        sale:'hot',
        URL_1:'/src/Images/product-3-1.jpg',
        URL_2:'/src/Images/product-3-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },
    {
        sale:'hot',
        URL_1:'/src/Images/product-9-1.jpg',
        URL_2:'/src/Images/product-9-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },
    {
        sale:'hot',
        URL_1:'/src/Images/product-10-1.jpg',
        URL_2:'/src/Images/product-10-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },
    {
        sale:'hot',
        URL_1:'/src/Images/product-4-1.jpg',
        URL_2:'/src/Images/product-4-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },
    {
        sale:'hot',
        URL_1:'/src/Images/product-5-1.jpg',
        URL_2:'/src/Images/product-5-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },
    {
        sale:'hot',
        URL_1:'/src/Images/product-6-1.jpg',
        URL_2:'/src/Images/product-6-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },
    {
        sale:'hot',
        URL_1:'/src/Images/product-7-1.jpg',
        URL_2:'/src/Images/product-7-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },
    {
        sale:'hot',
        URL_1:'/src/Images/product-8-1.jpg',
        URL_2:'/src/Images/product-8-2.jpg',
        Categrey:'Snak',
        Detail:'Seeds of Change Organic Quinoa, Brown, & Red Rice',
        rating:'(4.0)',
        Product:'nestfood',
        newPrice:'23$',
        oldPrice:'54$',
    },

]
export default Obj;